language: node_js
node_js:
  - "5.11"

after_success:
  - chmod +x ./scripts/*.sh
  - chmod +x ./scripts/for-travis/*.sh
  - ./scripts/for-travis/build-and-deploy.sh

env:
 global:
 - GH_REF: github.com/crewmeister/accurate-gps-position.git
 - secure: c1v/O+OKJe+Jn7vGmY8n1eRzLUlIP6W7KeK2nyZ5XJ+6SPMcXQnRaNfYlUgXrMWf3wKiwMmvS50GcQWr4Zftcc7x/oqnDPTpFh/WyGgtBAqF4Srx6m0dH1Doeje7E/hJpb0vqZsGJ2rp5q5cpFHhb4t80FoArr5DxLeEn4s3MnMF3CS4BVy2iXoQs1omZPAN0BN3pGNs5Y1oKym9KxqeQIw+g3ps1gTa8MtSIkEvkUy2UEKXIhq9tg4vZl7r8ju76Ec8iubqFmPgT036KdI/C9SL267eSp11qx05OP1umBrb2IF7/SHRKU6+ThXSX/R7NjWqWsEPPiE2TVPrbRAUYZIBKI7LlNnv4Gvq+oqoIOCqBe8nXwCZd9Woy0eyk9AWDij7GDqWVnBywijXpSEzPSUD1UptqErXyk6drIwD5YVV7kb1oZa91Xhbk2rQA4h7qqyfXGzZeHwmHayzpXlB4Nfq5UoWQDjxhKlQZ8NfzOR6XtVO7k+Wrk6N9e+X8LNnJ+aV6umJrk3ifqRSYGWAGp+Iw1dSYJlzE755Jcnktxv9kcnnE1I8JSHNV1FikS6P8cdzBRMvMrpXkZg8+/ESy7V+zHjrcqs/XfWVSNw4NQaCvX9WBexTjPq8TbtpoMu3UveYNgN98WOqeFT0LhTi1AHQq8Li7mm2HcuZKbJDxE0=
